import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ books }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>LibrosDEV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://nextjs.org">LibrosDEV</a>
        </h1>

        <p className={styles.description}>
          Agrega tus Libros de Programación Favoritos
        </p>

        <div className={styles.grid}>
        {books.map(book => (
          <div key={book.ISBN} className={styles.card}>
            <h2>{book.title}</h2>
            <ul>
              {book.authors.map(author =>  (
                <li key={author}>{author}</li>
              ))}
            </ul>
          </div>
        ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  // const API_URL = process.env.API_URL || 'http://localhost:3000'
  // const res = await fetch(`${API_URL}/api/books`);
  // const books = await res.json();

  const books = [
    {
      title: "Aprendiendo JavaScript",
      ISBN: "9788700179263",
      authors: ["Carlos Azaustre"],
      cover: "blank.png",
    },
    {
      title: "Clean JavaScript",
      ISBN: "979856783319",
      authors: ["Miguel A. Gómez"],
      cover: "blank.png",
    },
    {
      title: "MERN Guía Práctica de Aplicaciones Web",
      ISBN: "9788418551055",
      authors: [
        "Jesús Fontecha",
        "Manuel Ángel Serrano",
        "Iván González",
        "Ramón Hervás",
      ],
      cover: "blank.png",
    },
    {
      title: "Cracking the Coding Interview",
      ISBN: "9780984782857",
      authors: ["Gayle Laakmann McDowell"],
      cover: "blank.png",
    },
  ];

  return {
    props: {
      books,
    },
    revalidate: 10,
  }
}
